### LOGIN AL SISTEMA: obtiene el token BEARER que debe ser usado en todas las
### pruebas posteriores (copiando el mismo en cada caso). Si expira la sesion
### de usuario, entonces hay que logearse de nuevo (el tiempo de sesion puede
### agrandarse con la propiedad: application.jws.token_duration -esta en 180)

POST http://127.0.0.1:8080/auth/login
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: Basic NDM1Zjk5NjgtZjY0My00N2U5LTlkMTU6MjNhNWNiMzYxYjFk

{ "username":"jmfragueiro","password":"fito" }

### LISTA LOS USUARIOS DE LA BASE

GET http://127.0.0.1:8080/user
Accept: */*
Cache-Control: no-cache
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJraWQiOiJtYmVzciIsImFsZyI6IkhTNTEyIn0.eyJqdGkiOiI5Y2M4NTM1Yi1kZDM5LTRiNTctOWM1Ny0yZWY4NDlmZmE4MzEiLCJzdWIiOiJqbWZyYWd1ZWlybyIsImlhdCI6MTc0Nzc2MDA1MywiZXhwIjoxNzQ3NzYwMjMzLCJhdXRob3JpdGllcyI6WyJST0xFX0FETUlOIl19.FQzVcXRVIkyOATGoCJLdOMHypw3cZ9eVHWAVqiIsUXNlcxkKg80EK76WQk6mIY1Jk7_kzYZFWF1u_zZlBJrnNQ

### OBTIENE UN USUARIO EN PARTICULAR: el unico creado y con ID fijo

GET http://127.0.0.1:8080/user/b3f2ebd3-4434-47b0-95ed-1a3f48825069
Accept: */*
Cache-Control: no-cache
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJraWQiOiJtYmVzciIsImFsZyI6IkhTNTEyIn0.eyJqdGkiOiI5Y2M4NTM1Yi1kZDM5LTRiNTctOWM1Ny0yZWY4NDlmZmE4MzEiLCJzdWIiOiJqbWZyYWd1ZWlybyIsImlhdCI6MTc0Nzc2MDA1MywiZXhwIjoxNzQ3NzYwMjMzLCJhdXRob3JpdGllcyI6WyJST0xFX0FETUlOIl19.FQzVcXRVIkyOATGoCJLdOMHypw3cZ9eVHWAVqiIsUXNlcxkKg80EK76WQk6mIY1Jk7_kzYZFWF1u_zZlBJrnNQ

### CREA UN NUEVO USUARIO: con 2 telefonos

POST http://127.0.0.1:8080/user
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: Bearer eyJraWQiOiJtYmVzciIsImFsZyI6IkhTNTEyIn0.eyJqdGkiOiI5Y2M4NTM1Yi1kZDM5LTRiNTctOWM1Ny0yZWY4NDlmZmE4MzEiLCJzdWIiOiJqbWZyYWd1ZWlybyIsImlhdCI6MTc0Nzc2MDA1MywiZXhwIjoxNzQ3NzYwMjMzLCJhdXRob3JpdGllcyI6WyJST0xFX0FETUlOIl19.FQzVcXRVIkyOATGoCJLdOMHypw3cZ9eVHWAVqiIsUXNlcxkKg80EK76WQk6mIY1Jk7_kzYZFWF1u_zZlBJrnNQ

{
    "name": "liomessi",
    "email": "liomessi10@acme.cl",
    "password": "Hunter2@3!",
    "phones": [
        {
            "number": "4363178",
            "citycode": "376",
            "countrycode": "54"
        },
        {
            "number": "4588590",
            "citycode": "376",
            "countrycode": "54"
        }
    ]
 }

### CREA UN NUEVO USUARIO: con 1 telefono

POST http://127.0.0.1:8080/user
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: Bearer eyJraWQiOiJtYmVzciIsImFsZyI6IkhTNTEyIn0.eyJqdGkiOiI5Y2M4NTM1Yi1kZDM5LTRiNTctOWM1Ny0yZWY4NDlmZmE4MzEiLCJzdWIiOiJqbWZyYWd1ZWlybyIsImlhdCI6MTc0Nzc2MDA1MywiZXhwIjoxNzQ3NzYwMjMzLCJhdXRob3JpdGllcyI6WyJST0xFX0FETUlOIl19.FQzVcXRVIkyOATGoCJLdOMHypw3cZ9eVHWAVqiIsUXNlcxkKg80EK76WQk6mIY1Jk7_kzYZFWF1u_zZlBJrnNQ

{
    "name": "maradona",
    "email": "diego10@acme.cl",
    "password": "Pelus@3!",
    "phones": [
        {
            "number": "4399178",
            "citycode": "11",
            "countrycode": "54"
        }
    ]
 }

### FALLA AL CREAR UN USUARIO CON EMAIL REPETIDO

POST http://127.0.0.1:8080/user
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: Bearer eyJraWQiOiJtYmVzciIsImFsZyI6IkhTNTEyIn0.eyJqdGkiOiI5Y2M4NTM1Yi1kZDM5LTRiNTctOWM1Ny0yZWY4NDlmZmE4MzEiLCJzdWIiOiJqbWZyYWd1ZWlybyIsImlhdCI6MTc0Nzc2MDA1MywiZXhwIjoxNzQ3NzYwMjMzLCJhdXRob3JpdGllcyI6WyJST0xFX0FETUlOIl19.FQzVcXRVIkyOATGoCJLdOMHypw3cZ9eVHWAVqiIsUXNlcxkKg80EK76WQk6mIY1Jk7_kzYZFWF1u_zZlBJrnNQ

{
    "name": "mailrepet",
    "email": "diego10@acme.cl",
    "password": "BadMail@35!",
    "phones": [
        {
            "number": "1599178",
            "citycode": "021",
            "countrycode": "54"
        }
    ]
 }

### LISTA LOS USUARIOS DE LA BASE

GET http://127.0.0.1:8080/user
Accept: */*
Cache-Control: no-cache
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJraWQiOiJtYmVzciIsImFsZyI6IkhTNTEyIn0.eyJqdGkiOiI5Y2M4NTM1Yi1kZDM5LTRiNTctOWM1Ny0yZWY4NDlmZmE4MzEiLCJzdWIiOiJqbWZyYWd1ZWlybyIsImlhdCI6MTc0Nzc2MDA1MywiZXhwIjoxNzQ3NzYwMjMzLCJhdXRob3JpdGllcyI6WyJST0xFX0FETUlOIl19.FQzVcXRVIkyOATGoCJLdOMHypw3cZ9eVHWAVqiIsUXNlcxkKg80EK76WQk6mIY1Jk7_kzYZFWF1u_zZlBJrnNQ

### AGREGA UN TELEFONO AL UN USUARIO: hay que cambiar en la URL el ID de usuario con uno de los creados

POST http://127.0.0.1:8080/user/4defccbe-78bb-4cd8-a3e3-09af3a562af1/phones
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: Bearer eyJraWQiOiJtYmVzciIsImFsZyI6IkhTNTEyIn0.eyJqdGkiOiI5Y2M4NTM1Yi1kZDM5LTRiNTctOWM1Ny0yZWY4NDlmZmE4MzEiLCJzdWIiOiJqbWZyYWd1ZWlybyIsImlhdCI6MTc0Nzc2MDA1MywiZXhwIjoxNzQ3NzYwMjMzLCJhdXRob3JpdGllcyI6WyJST0xFX0FETUlOIl19.FQzVcXRVIkyOATGoCJLdOMHypw3cZ9eVHWAVqiIsUXNlcxkKg80EK76WQk6mIY1Jk7_kzYZFWF1u_zZlBJrnNQ

{
    "number": "123456",
    "citycode": "376",
    "countrycode": "54"
}

### DESACTIVA UN USUARIO: hay que cambiar en la URL el ID de usuario con uno de los creados

PUT http://127.0.0.1:8080/user/4defccbe-78bb-4cd8-a3e3-09af3a562af1/active/false
Accept: */*
Cache-Control: no-cache
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJraWQiOiJtYmVzciIsImFsZyI6IkhTNTEyIn0.eyJqdGkiOiIwNGNhYzg2NC1hNjA1LTQ0MDEtOWE1Yy1iZDYwOTAyM2Q2ZmIiLCJzdWIiOiJqbWZyYWd1ZWlybyIsImlhdCI6MTc0Nzc2MDI0MCwiZXhwIjoxNzQ3NzYwNDIwLCJhdXRob3JpdGllcyI6WyJST0xFX0FETUlOIl19.DVRjwIvLxDpctc6VUhONL_HGLA_YNuNMe06efnnLT342KfE9q9y990J8SX1lFctrs_RJDwIMOkY1nl_sYx4l_g

### LISTA LOS USUARIOS DE LA BASE (se ve el usuario desactivado)

GET http://127.0.0.1:8080/user
Accept: */*
Cache-Control: no-cache
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJraWQiOiJtYmVzciIsImFsZyI6IkhTNTEyIn0.eyJqdGkiOiIwNGNhYzg2NC1hNjA1LTQ0MDEtOWE1Yy1iZDYwOTAyM2Q2ZmIiLCJzdWIiOiJqbWZyYWd1ZWlybyIsImlhdCI6MTc0Nzc2MDI0MCwiZXhwIjoxNzQ3NzYwNDIwLCJhdXRob3JpdGllcyI6WyJST0xFX0FETUlOIl19.DVRjwIvLxDpctc6VUhONL_HGLA_YNuNMe06efnnLT342KfE9q9y990J8SX1lFctrs_RJDwIMOkY1nl_sYx4l_g

### BORRA UN USUARIO: hay que cambiar en la URL el ID de usuario con uno de los creados

DELETE http://127.0.0.1:8080/user/4defccbe-78bb-4cd8-a3e3-09af3a562af1
Accept: */*
Cache-Control: no-cache
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJraWQiOiJtYmVzciIsImFsZyI6IkhTNTEyIn0.eyJqdGkiOiIwNGNhYzg2NC1hNjA1LTQ0MDEtOWE1Yy1iZDYwOTAyM2Q2ZmIiLCJzdWIiOiJqbWZyYWd1ZWlybyIsImlhdCI6MTc0Nzc2MDI0MCwiZXhwIjoxNzQ3NzYwNDIwLCJhdXRob3JpdGllcyI6WyJST0xFX0FETUlOIl19.DVRjwIvLxDpctc6VUhONL_HGLA_YNuNMe06efnnLT342KfE9q9y990J8SX1lFctrs_RJDwIMOkY1nl_sYx4l_g

### LISTA LOS USUARIOS DE LA BASE (ya no está el usuario borrado)

GET http://127.0.0.1:8080/user
Accept: */*
Cache-Control: no-cache
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJraWQiOiJtYmVzciIsImFsZyI6IkhTNTEyIn0.eyJqdGkiOiIwNGNhYzg2NC1hNjA1LTQ0MDEtOWE1Yy1iZDYwOTAyM2Q2ZmIiLCJzdWIiOiJqbWZyYWd1ZWlybyIsImlhdCI6MTc0Nzc2MDI0MCwiZXhwIjoxNzQ3NzYwNDIwLCJhdXRob3JpdGllcyI6WyJST0xFX0FETUlOIl19.DVRjwIvLxDpctc6VUhONL_HGLA_YNuNMe06efnnLT342KfE9q9y990J8SX1lFctrs_RJDwIMOkY1nl_sYx4l_g

### MODIFICA UN USUARIO: hay que cambiar en el body el ID de usuario con uno de los creados

PUT http://127.0.0.1:8080/user
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: Bearer eyJraWQiOiJtYmVzciIsImFsZyI6IkhTNTEyIn0.eyJqdGkiOiIwNGNhYzg2NC1hNjA1LTQ0MDEtOWE1Yy1iZDYwOTAyM2Q2ZmIiLCJzdWIiOiJqbWZyYWd1ZWlybyIsImlhdCI6MTc0Nzc2MDI0MCwiZXhwIjoxNzQ3NzYwNDIwLCJhdXRob3JpdGllcyI6WyJST0xFX0FETUlOIl19.DVRjwIvLxDpctc6VUhONL_HGLA_YNuNMe06efnnLT342KfE9q9y990J8SX1lFctrs_RJDwIMOkY1nl_sYx4l_g

{
    "id": "e0382caa-124a-4d60-8967-0f2dca916a4d",
    "name": "liomessi12",
    "email": "lmessi10@acme.cl",
    "password": "Hunter2@3!",
    "phones": []
 }

### TERMINA LA SESION

POST http://127.0.0.1:8080/auth/logout
Accept: */*
Cache-Control: no-cache
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJraWQiOiJtYmVzciIsImFsZyI6IkhTNTEyIn0.eyJqdGkiOiIwNGNhYzg2NC1hNjA1LTQ0MDEtOWE1Yy1iZDYwOTAyM2Q2ZmIiLCJzdWIiOiJqbWZyYWd1ZWlybyIsImlhdCI6MTc0Nzc2MDI0MCwiZXhwIjoxNzQ3NzYwNDIwLCJhdXRob3JpdGllcyI6WyJST0xFX0FETUlOIl19.DVRjwIvLxDpctc6VUhONL_HGLA_YNuNMe06efnnLT342KfE9q9y990J8SX1lFctrs_RJDwIMOkY1nl_sYx4l_g

###
